INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris frankiert Briefe mit seinem Passfoto.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris frankiert Briefe mit seinem Passfoto.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Es gibt feindliche Aliens. Sie warten nur bis Chuck Norris gestorben ist, um angreifen zu können.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Heute weiß man, warum ich das Universum ausdehnt. Alles versucht, sich so weit wie möglich von Chuck Norris zu entfernen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wenn Monster schlafen gehen, schauen sie vorher, ob Chuck Norris unterm Bett ist.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris braucht keine Waschmaschine. Der Dreck verschwindet freiwillig von seiner Kleidung.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wenn Chuck Norris zu seinem Hund “Sitz!” sagt, setzten sich all Leute, die es gehört haben.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris ist bereits vor zehn Jahren gestorben. Der Tod hatte aber nicht den Mut, es ihm zu sagen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris hatte einen Gerichtstermin. Aber der Richter ist nicht erschienen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wenn Chuck Norris beim Schwarzfahren erwischt wird zahlt der Schaffner die Strafe.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris liest keine Bücher. Er starrt sie so lange an, bis sie ihm freiwillig sagen, was er wissen will.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Vor kurzem hat die Polizei Chuck Norris in seinem Auto angehalten, weil Chuck auf der Autobahn 200 statt 100 gefahren ist. Es kam schnell zu einer Einigung. Die Polizei durfte mit einer mündlichen Verwarnung weiterfahren.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris wird niemals eine Herzattacke bekommen. Sein Herz wird es nicht wagen, ihn zu attackieren.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris feiert keinen Geburtstag, der Geburtstag feiert ihn.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wenn Chuck Norris in den Himmel schaut, fangen die Wolken an zu schwitzen. Dieses Phänomen wurde Regen genannt.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris bekommt auch Geld für Flaschen ohne Pfand.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris verwählt sich nicht. Wenn du abhebst, warst du am falschen Telefon.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Käfige zum Tauchen mit Haien wurden erfunden, damit sich die Haie sicherer fühlen, wenn Chuck Norris im Meer schwimmt.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris braucht keinen Regenschirm – die Regentropfen trauen sich nicht, auf ihm zu landen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris bestellt Chicken McNuggets bei Burger King und bekommt sie auch.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Der Akku von Chuck Norris‘ Smartphone ist schon seit drei Monaten leer, aber es traut sich nicht auszugehen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann Feuer mit einer Lupe machen – nachts!', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris läuft 100 Meter in einer Sekunde. Er kennt immer eine Abkürzung.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Am Anfang war nichts. Dann hat Chuck Norris dem Nichts einen Roundhouse-Kick verpasst und gesagt: „Besorg dir ‘nen Job.“ Das ist die Geschichte des Universums.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann ein Feuer entfachen, indem er zwei Eiswürfel aneinander reibt.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris wurde gestern geblitzt – beim Einparken.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wenn man Chuck Norris fragt, wie viele Liegestütze er schafft, antwortet er: „Alle.“', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann ein Fünfeck zeichnen – mit vier Strichen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris entführt Aliens.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Der Bart von Chuck Norris verdeckt nicht sein Kinn, sondern eine weitere Faust.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann Drehtüren zuknallen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann Atom- von Ökostrom unterscheiden – und zwar am Geschmack.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wenn Chuck Norris mit nassen Fingern an der Steckdose rumfummelt, kriegt das Kraftwerk einen Schlag.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris hat bis Unendlich gezählt. Zweimal.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris grillt unter Wasser.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wenn Chuck Norris ins Wasser fällt, wird er nicht nass – das Wasser wird Chuck Norris.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris ist der einzige Mensch, der die Zeit wirklich totschlagen kann.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris trinkt aus der Wasserleitung. Auf ex.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wenn Chuck Norris Liegestütze macht, drückt er die Welt nach unten.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Das einzige Mal, dass Chuck Norris sich irrte, war als er dachte, er hätte sich geirrt.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris hat als Kind Sandburgen gebaut. Man nennt sie heute Pyramiden.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris isst chinesisches Essen mit einem Stäbchen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann Quadrate mit einer Winkelsumme von 380 Grad zeichnen. Als sein Mathematiklehrer das bemerkte, ist er verrückt geworden.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris Computer hat keine Löschen-Taste, denn er macht keine Fehler.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris atmet nicht. Er hält die Luft als Geisel.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris verzichtet auf seine Rechte – seine Linke ist sowieso schneller.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris’ wollte Cowboy-Stiefel. Dazu brauchte er nur zwei echte Cowboys.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Menschen malen den Teufel an die Wand. Der Teufel malt Chuck Norris an die Wand.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris sucht nicht die Nadel im Heuhaufen – er sucht den Heuhalm im Nadelhaufen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann über seinen eigenen Schatten springen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Hans-Dieter trägt Socken in Sandalen. Chuck Norris Stilbewusstsein zwingt ihn, Hans-Dieter einen Roundhouse-Kick zu verpassen – wegen Sandalismus.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris hat schon mehr Leute vermöbelt als IKEA.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wenn Chuck Norris sich aussperrt, ist er alles andere als aus dem Häuschen, er reißt die Wand ein und ist wieder drin.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris trinkt ausschließlich Guinness, weil er jeden Guinness-Weltrekord hält.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris lacht nicht nur zuletzt, sondern auch zuerst am besten.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wimpern hat Chuck Norris nicht. Das sind AUGENBÄRTE.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris ist so männlich, dass seine Brusthaare Brusthaare haben.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris Tränen können alle Krankheiten der Menschen heilen, doch er weint nie.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Als Chuck Norris geboren wurde, sagte der Arzt zur Mutter: „Glückwunsch, es ist ein MANN!“', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Nach dem Bartschneiden, muss die Polizei Chuck Norris Barthaare entsorgen – sie fallen unter das Waffengesetz.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris hat alle Farben erfunden, außer Rosa, das hat Tom Cruise erfunden.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris hat keine Türen in seinem Haus, er geht lieber durch Wände.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Es gibt einen Stoff, der härter ist als Diamant – die Barthaare von Chuck Norris.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris ist weder männlich noch weiblich, er hat sein eigenes Geschlecht – Chuck Norris.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris macht Liegestütze und Sit-ups zur gleichen Zeit.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris braucht ein Stunt-Double, aber nur in Szenen, in denen er weinen soll.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Es gibt keinen Klimawandel. Chuck Norris ist einfach zu heiß für diese Welt.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris hatte in seinem Leben nur einmal Todesangst: Als er sich das erste Mal im Spiegel gesehen hat.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris benutzt keine Anmachsprüche. Er sagt einfach: „Jetzt.“', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris rasiert sich nicht. Er schärft die Klinge an seinem Bart.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann ein Sandwich bei Subway bestellen – ohne eine Frage zu beantworten.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann den Klitschko-Brüdern unbeschadet die Milchschnitte wegnehmen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Als James Cameron den Film Terminator produziert hat, wollte er eigentlich Chuck Norris als Hauptdarsteller. Dann hat Cameron aber gemerkt, dass der Film damit ja eine Dokumentation und keine Fiktion mehr gewesen wäre.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris wusste warum Hodor „Hodor“ heißt – schon bevor Game of Thrones geschrieben wurde.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris hat einmal mit einem Mann gewettet, dass er von einem Hochhaus springen kann, ohne sich zu verletzen. Der Verlierer musste seine Unterhose künftig über der Hose tragen. Superman verlor.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Popeye isst Spinat. Chuck Norris isst Popeye.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann ein Happy Meal zum Weinen bringen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris bekommt bei Praktiker 20 Prozent auf alles. Auch auf Tiernahrung.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wenn Bruce Banner wütend ist, wird er zu Hulk. Wenn Hulk wütend ist, wird er zu Chuck Norris.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris weiß, warum da Stroh liegt.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Sido hat mal gefragt, wer eigentlich Chuck Norris ist. Seitdem trägt er eine Maske.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('In dem Film „Die Todeskralle schlägt wieder zu“ wurde Chuck Norris von Bruce Lee besiegt. Dieser Spezialeffekt hat so viel Geld gekostet, dass die Zentralbanken mehr Geld drucken und sich eine neue Zahl ausdenken mussten – die Zentilliarde.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann eine 5 Minuten Terrine in 30 Sekunden zubereiten.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wer bei Scrabble Chuck Norris legt, hat gewonnen – für immer.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris hat bei Burger King bestellt und seine Bestellung war vollständig.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris hat Speedy Gonzales gefangen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Voldemort nennt Chuck-Norris „Du-weißt-schon-wer“.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann Griechenland retten.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris besiegt den Nachtkönig.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Peter Zwegat hat Schulden bei Chuck Norris.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kennt das Ende von GZSZ.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Die Namen, die am Ende jeder Episode von „Walker, Texas Ranger“ im Abspann laufen, sind keine Credits: Es ist in Wirklichkeit eine Liste der Personen, denen Chuck Norris an dem Tag einen Roundhouse-Kick verpasst hat.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Arnold Schwarzenegger musste wegen schweren Verletzungen ins Krankenhaus eingeliefert werden. Chuck Norris hatte ihn auf Facebook angestupst.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Die GEZ zahlt Chuck-Norris-Gebühren.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris war auf dem Mars. Das ist der Grund dafür, warum es dort kein Leben mehr gibt.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris ist nicht Gott. Nein, er kennt keine Gnade.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wie hört es sich an, wenn Chuck Norris angeln geht? – Du, du und du: Rauskommen!', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris ertränkt Fische.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Was geht Chuck Norris’ Opfern als letztes durch den Kopf? – Sein Fuß.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris ist so gefährlich, er hat schon sein Spiegelbild umgebracht.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris hat recht, es gibt keine Evolutionstheorie. Es gibt nur eine Liste von Lebewesen, denen Chuck Norris erlaubt zu leben.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Das Tote Meer hieß ursprünglich Lebenssee – bis Chuck Norris darin baden ging.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris wurde mal auf Latein beleidigt – seitdem gilt es als tote Sprache.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris geht nicht jagen, denn das beinhaltet potentielles Versagen. Chuck Norris geht töten.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Jesus, ein Priester und Chuck Norris saßen in einem Boot auf dem Ozean.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann in einer Moschee das Halleluja anstimmen – und jeder singt mit.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('In einem normalen, durchschnittlich bestückten Wohnzimmer gibt es 1442 Dinge, die Chuck Norris benutzen kann, um dich zu töten. Den Raum selbst eingeschlossen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris ist gestern gestorben. Heute geht es ihm schon wieder besser.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris hat einen Grizzlybär-Teppich. Der Bär lebt, aber hat Angst, sich zu bewegen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris bringt Zwiebeln zum Weinen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris schafft seinen Bachelor unter der Regelstudienzeit.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Die Erde dreht sich nur, weil Chuck Norris ihr einen Roundhouse-Kick verpasst hat.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kennt die letzte Ziffer von Pi.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris kann schneller stehen, als andere rennen können.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Die Zeit rennt, um Chuck Norris zu entkommen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris darf während der Fahrt mit dem Busfahrer sprechen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Wenn Google etwas nicht findet, fragt es Chuck Norris. (Marc Kue)', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris niest mit offenen Augen.', NOW());
INSERT INTO joke (joke_text, creation_date) VALUES ('Chuck Norris isst sein Knoppers schon um neun Uhr morgens in Deutschland.', NOW());